name: storybook_ds
description: Storybook Uma forma de apresentar os componentes de qualquer Design System
homepage: https://github.com/jheimes-silveira/storybook_ds
version: 1.1.0+17

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
